version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running tests...
      - pytest --cov=. --cov-fail-under=70
  post_build:
    commands:
      - echo Finish build...
artifacts:
  files:
    - '**/*'